import sys
import os
import argparse
import numpy as np
from tqdm import tqdm
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

# Add parent directory to path so imports work from any location
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from envs.decoder_env_v2 import DecoderEnvV2, NUM_DECODERS

def evaluate_agent(model_path: str, data_dir: str, output_schedule_path: str):
    print(f"Loading environment with dataset from folder: {data_dir}")
    
    # We pass is_eval=True so the environment loads the held-out validation images!
    raw_env = DecoderEnvV2(data_dir=data_dir, train_split_pct=0.8, is_eval=True)
    env = DummyVecEnv([lambda: raw_env])
    
    print(f"Loading trained model from: {model_path}")
    try:
        model = PPO.load(model_path)
    except Exception as e:
        print(f"Failed to load model: {e}")
        return

    print("\nStarting evaluation episode...")
    obs = env.reset()
    done = False
    
    # Record the schedule generated by the agent
    schedule = []
    
    # Track commands for progress bar and deadlock detection
    initial_cmds = sum(len(q) for q in raw_env.cmds)
    last_remaining_cmds = initial_cmds
    cycles_stalled = 0
    
    pbar = tqdm(total=initial_cmds, desc="Processing Commands", unit="cmd")
    
    while not done:
        # deterministic=True ensures the agent picks the argmax action instead of sampling
        action, _states = model.predict(obs, deterministic=True)
        
        # SB3 vec envs return arrays, so we extract the scalar action
        action_scalar = int(action[0])
        schedule.append(action_scalar)
        
        obs, rewards, dones, infos = env.step(action)
        
        # In a DummyVecEnv, 'dones' is an array of booleans
        done = dones[0]
        
        if done:
            pbar.update(last_remaining_cmds) # Fill the progress bar completely
            break
            
        # Deadlock detection & Progress updates
        current_remaining_cmds = sum(len(q) for q in raw_env.cmds)
        consumed = last_remaining_cmds - current_remaining_cmds
        
        if consumed > 0:
            pbar.update(consumed)
            cycles_stalled = 0
        else:
            cycles_stalled += 1
            
        if cycles_stalled >= 500:
            pbar.close()
            print("\n[ERROR] Simulation aborted: Agent spent 500 cycles without consuming any new commands (Deadlock).")
            return
            
        last_remaining_cmds = current_remaining_cmds
        
    pbar.close()
        
    # The environment automatically resets on 'done' when using DummyVecEnv, 
    # but the final info dict from the terminal step is stored in infos[0].
    # (If using standard gym env, it would just be 'info')
    final_info = infos[0]
    
    makespan = final_info.get("makespan", len(schedule))
    decoder_times = final_info.get("decoder_times", [0]*NUM_DECODERS)
    
    # Calculate action distribution
    action_counts = np.bincount(schedule, minlength=NUM_DECODERS)
    action_pcts = (action_counts / len(schedule)) * 100
    
    print("\n" + "="*50)
    print("EVALUATION RESULTS")
    print("="*50)
    print(f"Total Cycles (Makespan): {makespan}")
    print(f"Total Actions Scheduled: {len(schedule)}")
    print("\nDecoder Active Cycles (Load Balance):")
    for i, time_val in enumerate(decoder_times):
        print(f"  SubDecoder {i}: {time_val} cycles")
        
    print("\nBus Routing Distribution:")
    for i, pct in enumerate(action_pcts):
        print(f"  SubDecoder {i}: {action_counts[i]} beats ({pct:.1f}%)")
        
    # Save the schedule to a file for deployment
    try:
        with open(output_schedule_path, 'w') as f:
            # Write comma-separated actions
            f.write(",".join(map(str, schedule)))
        print(f"\nStatic routing schedule successfully saved to: {output_schedule_path}")
    except Exception as e:
        print(f"\nFailed to save schedule: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate a trained PPO agent on DecoderEnvV2.")
    parser.add_argument("--model_path", type=str, required=True,
                        help="Path to the trained .zip model file.")
    parser.add_argument("--data_dir", type=str, default="sample_data",
                        help="Path to the top-level folder containing test images.")
    parser.add_argument("--output", type=str, default="generated_schedule.txt",
                        help="Path to save the generated static schedule text file.")
    
    args = parser.parse_args()
    
    evaluate_agent(args.model_path, args.data_dir, args.output)